### ISSUE TITLE
no openQA data on metrics.o.o

### ISSUE THREAD

**Issue by ggardet** [openSUSE/openSUSE-release-tools#2672] opened 2021-11-24 10:16 UTC
There is no openQA data on metrics.o.o since june 2020. See: https://metrics.opensuse.org/d/osrt_openqa/osrt-openqa?orgId=1&from=now-600d&to=now

Any idea where the issue is?

**Comment by ggardet** [comment] 2021-11-24 10:17
Cc @okurz

**Comment by okurz** [comment] 2021-11-24 14:08
I think I answered you in chat some time ago as well. It's unfortunate that there is no updated data. I am not aware of any changes on openQA side that might have caused this. AFAIK metrics.opensuse.org is effectively unmaintained and would need someone stepping up, getting access, e.g. as [openSUSE Heroes](https://en.opensuse.org/openSUSE:Heroes) member.

**Comment by okurz** [comment] 2021-11-24 14:12
By the way, the data likely was read from the route that still exists and provides valid, up-to-date data over https://openqa.opensuse.org/admin/influxdb/jobs

**Comment by ddemaio** [comment] 2021-11-24 15:41
@okurz someone from openQA can help out and ping @witekest for help if they have questions on the openQA portion. It's python scripts from what I understand.

**Comment by okurz** [comment] 2021-12-08 11:30
Thanks. We could fix the problem right now. https://metrics.opensuse.org/d/osrt_openqa/osrt-openqa?orgId=1 fixed \o/
The problem is fixed with https://github.com/openSUSE/openSUSE-release-tools/pull/2673

**Comment by DimStar77** [comment] 2022-02-14 13:51
> The problem is fixed with #2673

**Closed by DimStar77** 2022-02-14 13:51 UTC
