### ISSUE TITLE
Competing SRs for the packagelist

### ISSUE THREAD

**Issue by gyr** [openSUSE/openSUSE-release-tools#1833] opened 2019-01-15 16:07 UTC
Scenario:
Using gitlab-pipeline and having 2 or more staging projects falling due to Package List Generator reported a mismatch between the calculated package list and the reference.

In order to fix them SRs for 000package-groups must be submitted.

Problem:
The SRs can not be done in parallel due to OBS is not able to "merge" SRs that touch the same file (000package-groups). So, staging projects must be fixed sequentially, e.g. fix the first staging project then rebase (freeze) the second staging to get latest 000package-groups and then fix it, repeat this process for the subsequent falling staging projects.

**Comment by gyr** [comment] 2019-01-16 16:47
Possible solution:
Instead of require a SR to fix it, a bot will provide a comment with the 000package_list diff, leaving the decision to accept or not for the user. If so the diff will be applied within the pipeline (retrigger the pipeline and apply the diff on staging accepts).

**Comment by nilxam** [comment] 2019-01-17 04:08
An option can be:

Don't submit groups.yml change directly against 000package-groups but from another package.

Eg. having a `000package-groups-change` with the content like:

<pre>
sle_module_desktop_applications: includes - XXX
sle_module_desktop_applications: excludes - XXX
</pre>

then extend the pkglistgen to be can process this change and apply it to `000package-groups` in each staging if `000package-groups-change` exists. Additionally to that, `000package-group` must not be from frozenlinks, but an instantiated `000package-group` in each staging what linked to last revision in main project's one. The last step is copy `000package-groups` content to main project and decline `000package-groups-change` when doing *staging accept*. We can also *re-create* `000package-groups` package in every staging project during a *staging accept*(then pkglistgen will re-processing it per 000package-groups-change if it exists).

hmm... not sure whether this sounds over engineering though.

**Comment by jberry-suse** [comment] 2019-05-21 03:12
> The SRs can not be done in parallel due to OBS is not able to "merge" SRs that touch the same file (000package-groups).

Seems like the crux of the problem is a VCS one then. Assuming the lines are not overlapping this would be trivial with git as is done with pull requests even in this repository. We can over-engineer a workaround as the majority of the code in this repository although this one breaks a lot of assumptions.

**Comment by coolo** [comment] 2019-05-21 04:37
OBS can handle merges as well (it even has extra code to merge .changes files) - that's not the problem. The problem is that the expected output is part of 000package-groups and the expected output depends on other changes in single staging projects.

**Comment by jberry-suse** [comment] 2019-06-04 12:58
> OBS can handle merges as well (it even has extra code to merge .changes files) - that's not the problem.

Seems this issue needs a proper description of the problem:

> The SRs can not be done in parallel due to OBS is not able to "merge" SRs that touch the same file (000package-groups).

If the main problem is multiple requests for the same package staged in different stagings that is a rather cumbersome break to our staging process assumptions. Since the package contains input and output for the tool what is the "preferred" or "expected" workflow we are trying to achieve?

**Comment by jberry-suse** [comment] 2019-07-02 13:20
frequency

- changing input in parallel is less common
- changing output in parallel is common

As such the primary goal is to remove the output from the request. The output is there to allow for release manager to verify the changes are desired and approve them. As such the approve and verify portion needs to be re-created outside of a diff in a request.

The approved changes from other stagings still needs to be updated when re-freezing. To keep that behavior the output is stored in a separate package apart from the one containing the input which is being updated, but still in the target project and thus frozen with the rest of the packages.

A check is created and set for staging projects with a link to the output changes and blocking until it is approved.

Approval consists of setting a new attribute on the staging project with the approved diff as the value. Once the tool diff (or lack of diff and lack of attribute) matches the attribute the check is considered passed. On accept the contents of the output package (or diff in attribute) need to be applied to the target project package.

This still leaves a problem when trying to change the input in parallel, but since requests are no longer necessary to approve output in parallel it should be much improved.

A staging plugin subcommand can be created for setting the attribute to the current diff in that staging. If exposed via operator server this could be presented as a button on the dashboard.

**Comment by coolo** [comment] 2019-07-02 14:27
thanks. that sums up nicely also what I understand

**Comment by DimStar77** [comment] 2019-07-03 09:41
> The approved changes from other stagings still needs to be updated when re-freezing. To keep that behavior the output is stored in a separate package apart from the one containing the input which is being updated, but still in the target project and thus frozen with the rest of the packages.

This can make it actually quite hard to find a time one can freeze stagings - as right after a staging accept, the 'input' files are updated in $target, but the output has not yet been calculated (and likely can't until most of the other packages are rebuilt too) - hence, rebasing at such a moment would keep the 'old' output in a staging, but the new input and sources.

**Comment by coolo** [comment] 2019-07-03 12:39
The output of $target does not matter here. We just have an expectation of what output in stagings looks like.  And we carry that around. The build state of $target does not matter.

**Comment by lnussel** [comment] 2019-08-29 08:39
I'm not sure the issue is properly understood. Just separating the output and approving diffs to it means the only thing that can be approved that way is new packages appearing in _unsorted_. Means there would be still no way to sort new subpackages in e.g staging A and C into any other group than _unsorted_.
If that is ok we could get away with a much cheaper implementation. Ie just don't assert zero diff on _unsorted_ in staging. Probably not even in main project.

Instead presentation of subpackage changes could be improved.
For example bots could report subpackage changes so relmgr review sees what's coming already and notifications could be sent if the _unsorted_ list changes in the main project.

**Comment by coolo** [comment] 2019-08-29 09:19
> I'm not sure the issue is properly understood. Just separating the output and approving diffs to it means the only thing that can be approved that way is new packages appearing in _unsorted_. Means there would be still no way to sort new subpackages in e.g staging A and C into any other group than _unsorted_.

Why's that?

> If that is ok we could get away with a much cheaper implementation. Ie just don't assert zero diff on _unsorted_ in staging. Probably not even in main project.
> 
> Instead presentation of subpackage changes could be improved.
> For example bots could report subpackage changes so relmgr review sees what's coming already and notifications could be sent if the _unsorted_ list changes in the main project.

I get the impression you misunderstand the problem.

**Comment by gyr** [comment] 2019-09-10 13:16
Confluence page created by SLE release team that summarizes the issue and get a common understand about it:

https://confluence.suse.com/display/~fcrozat/Packagelist+modification+issues

If you could please review it and provide your inputs, feedbacks and thoughts , so we can set the expectation on RM side.

**Comment by coolo** [comment] 2019-09-11 19:44
That page unfortunately doesn't actually add anything new. But what do we know about the subproblems and it's frequency?

a) maintenance only can have impact on mondays due to the snapshotting. If it has, all stagings are equally affected and you need to update the package lists of all stagings to match the new package set. That requires sometimes input change, but most weeks output changes. But no matter what, you still need to pass this through in one and rebase all others to match the sources with the binaries of the updates. Taking the package lists from $target without freeze sounds appealing for this use case, but has a lot of drawbacks. As such the work around suggested by @DimStar77 on Tuesday to link from 'the staging' to all others is still good enough. Aka 'rebase light' saves you time.

b) product changes standing on their own, e.g. changing milestone name or changing other product meta data. These require changes in input and often even adoptions of openQA tests, so there is a limit on what you want we can do with them in paralllel. But there are also other harmless cases like pulling package X one module level higher. This comes with an input change and a recalculated output. These are rather rare and are easy to merge to other stagings, so they don't harm the parallism.

c) new packages of a staging ending up in unsorted - this requires overwriting, because we actually want unsorted empty. So whenever we have that, we also require input changes - very similiar to case a), just that it's isolated to a staging while a) affects all. These happen a lot during alpha and beta phase, at least 3-4 times a week at peek times and ask mostly for parallelism.

d) package changes causing a change in output (by either new requires or new shared library names, or ...), not requiring a change in input, but approval of the output changes. They don't happen as often afaics, but are likely to interfere with the other cases. They can't be merged without sacrifising the isolation idea of staging. But these cases benefit most from what is suggested in Jimmy's comment of jul 2nd.

So all in all I guess if we go with split output, we still have no answer for c) - at least not for most cases there. And I even have my doubt a devel project would help - as again it would sacrifice the isolation of stagings (i.e. if one new package requires legal approval for weeks, you would have to rollback that change in the devel project to be able to proceed at all).

So the more we know about the problem, the more appealing is Max' 'overengineered' idea. But bringing these pieces together in a way that can be controlled by the RMs will be hard.

**Comment by coolo** [comment] 2020-03-21 10:22
Downgrading as SP2 has sailed without it

**Comment by coolo** [comment] 2022-03-19 06:45
So first step taken: pkglistgen will comment into the staging with the diff (in human readable form) in case of failure.

2nd step: accept an 'ignore' reply (in case where the output diff is created by maintenance or kernel version and the update is handled in another staging already). This avoids force accepts (which really, really need to stop) and will only affect the status sent back to IBS.

3rd step: accept an 'approve' reply to ACK the calculcated output changes. This will be a lot trickier - and I don't want to put too much pkglistgen specific things into accept, so I will have to come up with some kind of plugin system.

An important note: compared to the above lengthy comment, c) isn't as important any more as we no longer care so much about empty unsorted. Empty unsorted in stagings has little meaning (due to the other archs spilling different packages). So the unneeded.yml needs to be maintained with the target project in mind anyway, so it can be done in an input submission after accepting several stagings (and is mostly ignored for years).

**Comment by coolo** [comment] 2022-03-19 06:53
A little annoyance: after commenting the operator needs to restart the failing botmaster pipeline, but the OBS link goes straight to it and restarting will do. So no real worry.

**Comment by coolo** [comment] 2022-03-23 10:32
So 'ignore' has already proven useful for monday morning maintenance impact. Next (and final) step: act on 'approve' replies:
https://github.com/openSUSE/openSUSE-release-tools/pull/2761

With that I would close this ticket - to support parallel input changes is beyond what is reasonable IMHO.

**Closed by coolo** 2022-03-23 10:32 UTC
Labels: enhancement, P3
