### ISSUE TITLE
port to python 3

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1758] opened 2018-10-31 14:58 UTC
at some point we have to bite the bullet and go for python3. python package maintainers may push for removal of python2 from Factory in 2020...

**Comment by jberry-suse** [comment] 2018-10-31 20:09
Indeed, #1000. :)

**Comment by jberry-suse** [comment] 2018-11-01 00:58
Still dependent on `osc` switching first.

**Comment by coolo** [comment] 2018-11-01 11:50
I already did quite some python3 porting based on their branch. Most code works on 2 and 3 if written with that mind. But osc3 branch changed config parsing - and there I got stuck.

**Comment by jberry-suse** [comment] 2018-11-15 14:53
Created master-python3 branch to run against osc@python3 https://travis-ci.org/openSUSE/openSUSE-release-tools/branches.

**Comment by lethliel** [comment] 2018-11-15 15:05
The issue for problems and bugs for tools and plugins using the python3 branch on osc side is: https://github.com/openSUSE/osc/issues/467

**Comment by jberry-suse** [comment] 2018-11-15 16:50
This works run from `python3` branch of `osc`:

```
python2 ./osc-wrapper.py staging list
```

So perhaps comparability does work, but running from within python3 is only problem. I'll add python 3 to travis config for that temporary branch.

**Comment by jberry-suse** [comment] 2018-11-15 17:22
To be clear, running in python3 crashes:

```
$ ./osc-wrapper.py staging list
Traceback (most recent call last):
  File "/home/jberry/osc/osc/commandline.py", line 9229, in _load_plugins
    mod = imp.load_source(modname, os.path.join(plugin_dir, extfile))
  File "/usr/lib64/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jberry/.osc-plugins/osc-staging.py", line 20, in <module>
    from osclib.accept_command import AcceptCommand
  File "/home/jberry/.osc-plugins/osclib/accept_command.py", line 16, in <module>
    from osclib.core import source_file_load
  File "/home/jberry/.osc-plugins/osclib/core.py", line 27, in <module>
    from osclib.conf import Config
  File "/home/jberry/.osc-plugins/osclib/conf.py", line 3, in <module>
    from ConfigParser import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

/home/jberry/.osc-plugins/osc-staging.py: No module named 'ConfigParser'
```

as is already known.

After some tweaking of the build dependencies on travis I was able to get the tests to run in python 3 and reproduce the same problem on travis: https://travis-ci.org/openSUSE/openSUSE-release-tools/jobs/455601360. I also configured it to run daily to show results using latest upstreams.

Should provide a solid starting point and this branch can be re-based as further changes are made. I am getting the impression at this point that `osc@python3` run in python 2 may not be a problem which at least avoid short-term problems.

**Comment by jberry-suse** [comment] 2018-11-15 17:57
Created #1787 to provide the `osc@python3` test job in master and allow them to fail. This seems like the best approach.

**Comment by jberry-suse** [comment] 2018-11-15 18:04
The PR includes the following test jobs:
- python 2 & osc@master
- python 2 & osc@python3
- python 3 & osc@python3

**Comment by jberry-suse** [comment] 2018-11-15 18:07
Example: https://travis-ci.org/openSUSE/openSUSE-release-tools/builds/455617622.

**Comment by jberry-suse** [comment] 2018-11-15 18:11
Removed `master-python3` branch.

**Comment by jberry-suse** [comment] 2018-11-15 23:19
Reporting unnecessary API changes in the referenced `osc` issue.

**Comment by jberry-suse** [comment] 2018-11-16 21:52
It would likely be most effective to prioritize #1221, and some basic tests for most tools which should be simpler once we can do one of them properly (ex. all ReviewBots). Then we can rather quickly get a ~50+% increase in coverage and be more confidence all the code at least operating semi-sanely in ptyhon 3. Since running in python 3 is lower priority than be compatible with `osc@python3` this does not need to be done as quickly although it would also be helpful for checking compatibility.

**Comment by coolo** [comment] 2018-11-22 15:59
I'm not sure if this is bugged in osc or stagingapi, so I just put it here for now:

```
  File "/suse/coolo/.osc-plugins/osclib/stagingapi.py", line 1541, in update_status_comments
    meta['requests_comment'] = self.get_prj_meta_revision(project)
  File "/suse/coolo/.osc-plugins/osclib/stagingapi.py", line 690, in get_prj_meta_revision
    log = get_commitlog(self.apiurl, project, '_project', None, format='xml', meta=True)
  File "/space/prod/osc/osc/core.py", line 6329, in get_commitlog
    comment.replace('&', '&amp;').replace('<', '&gt;').replace('>', '&lt;'))
TypeError: a bytes-like object is required, not 'str'

**Comment by coolo** [comment] 2019-05-14 07:04
I'm closing this now in favor of individual tickets

**Closed by coolo** 2019-05-14 07:04 UTC
Labels: P2
