### ISSUE TITLE
origin-manager: consider allowing access to IBS requests

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1879] opened 2019-02-28 22:10 UTC
The more I've run into the issue leaper really needs to be able to check for parallel requests to SLE especially since that is the encouraged workflow now.

Something like https://build.opensuse.org/request/show/505009 should not require any human review and just wait for SLE submission just like Factory ones.

_Originally posted by @jberry-suse in https://github.com/openSUSE/openSUSE-release-tools/issues/944#issuecomment-309854776_

**Comment by jberry-suse** [comment] 2019-02-28 22:10
Not going to be part of milestone since more a policy decision and feature request than requirement.

**Comment by lnussel** [comment] 2019-03-01 10:00
that would mean precondition to running origin-manager would be to be able to access both IBS and OBS. Or we'd have to leak some information from IBS to OBS

**Comment by jberry-suse** [comment] 2019-03-01 20:03
Indeed. Which is more of a policy decision than implementation problem.

**Comment by coolo** [comment] 2021-07-21 14:46
It's not clear what the purpose of this ticket is - let's close this and have the policy discussion once we understand where the problem is

**Closed by coolo** 2021-07-21 14:46 UTC
Labels: enhancement
