### ISSUE TITLE
check_source doesn't pass a repo to view=info&parse=1

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/openSUSE-release-tools#2274] opened 2019-10-23 08:09 UTC
The values returned by `/source/prj/pkg?view=info&parse=1` depend on the repository, like `Name:` can be different depending on `%{suse_version}`.

Example: https://build.opensuse.org/request/show/741934

Question is where to get the repository name from...

**Comment by jberry-suse** [comment] 2019-10-24 12:45
If I am not mistaken this is a duplicate of #2244.

**Comment by Vogtinator** [comment] 2019-10-24 12:46
Kind of, but this isn't about .kiwi, it's about regular .spec files. Could be merged together by making #2244 more generic though.

**Comment by coolo** [comment] 2019-10-25 07:08
OMG. This will be so much fun.

**Closed** 2020-03-20 16:02 UTC
Labels: P2
