### ISSUE TITLE
origin-manager: Inconsistent output

### ISSUE THREAD

**Issue by crazyscientist** [openSUSE/openSUSE-release-tools#2506] opened 2020-12-08 16:37 UTC
Hi there,

while trying to figure out how to find all packages in Leap projects, that are inherited from SLE, I noticed one problem. I'd like to point out, that this could simply a configuration issue.

I ran the following two commands and got two different responses:

```
> osc -A https://api.opensuse.org origin --debug package -p openSUSE:Leap:15.2:Update zypper
[D] origin_find: openSUSE:Leap:15.2:Update/zypper with source 428296f (True, True, True)
[D] source_contain: SUSE:SLE-15:Update                       428296f == 428296f (match)
SUSE:SLE-15:Update

> osc -A https://api.opensuse.org origin --debug package -p openSUSE:Leap:15.2 zypper
[D] origin_find: openSUSE:Leap:15.2/zypper with source a27409a (True, True, True)
[D] source_contain: SUSE:SLE-15-SP2:GA                       a27409a == a27409a (match)
SUSE:SLE-15-SP2:GA
```

It's striking me as a bit odd, that the `:Update` project supposedly has an older origin project :thinking:

**Comment by msmeissn** [comment] 2020-12-18 10:24
The issue is that all SLES 15 GA / SP1 and SP2 have the same sources for zypper. 

The origin manager seems to look for source content diff, and as zypper (and libzypp and libsolv) are the same over GA/SP1/SP2 it selects one randomly or so.

**Comment by coolo** [comment] 2022-03-04 09:48
As 15.2 is EOL and 15.3ff follow a different approach, I'm going to close this now. See https://github.com/openSUSE/openSUSE-release-tools/pull/2730

**Closed by coolo** 2022-03-04 09:48 UTC
Labels: bug, P2
