### ISSUE TITLE
#2586 breaks detection of SLE-only patch removal

### ISSUE THREAD

**Issue by suntorytimed** [openSUSE/openSUSE-release-tools#2640] opened 2021-09-21 08:40 UTC
We have recently stumbled upon several declines of the factory-auto bot for SLE 15 SP4 submissions. It seems like PR #2586 is breaking a behaviour (or rather fixing a bug) we relied on in the SLE submit process. More specifically following change in line 216:

```
-    next unless $line =~ m/^+/;
+    next unless $line =~ m/^\+/;
```

We rely on this for cases in which a patch never got submitted to Factory but only in SLE (e. g. when Factory already has a newer version with the fix in it) and we want to sync the SLE version with the one from Factory again. This results in patches being dropped, which were never added to Factory. An example would be this submission: https://build.suse.de/request/show/252417

We have defined an exception for such cases in the Factory First Policy and openSUSE documentation, that it is enough to add those removed patches to the submit request message instead. (see https://en.opensuse.org/openSUSE:Creating_a_changes_file_(RPM)#Cross_Service-Pack_merges_for_SLE and “What if the changelog differs?” on https://wiki.suse.net/index.php/SUSE/Factory_First_Policy)

**Comment by DimStar77** [comment] 2021-09-21 08:45
The bug fix also made another thing impossible,namely 'revert submits' on TW:

Consider this:
* Package FOO is submitted from the devel prj to rev 2, it adds a patch
* the SR is accepted (passed all tests)
* As RelMgr I realize it causes way too much havoc, bugs found, fails, whatever, so I create an sr to revert to rev 1 (`osc sr openSUSE:Factory FOO -r 1 openSUSE:Factory -m "Revert" --nodevel`)

This revert will also make the patch vanish; due to the bug, this was accepted so far, newly this will fail.

The logic to limit to lines starting with `+` in the diff is this causing some trouble (we should also consider `-` lines)

**Comment by DimStar77** [comment] 2021-09-21 08:52
```
-    next unless $line =~ m/^\+/;
+    next unless $line =~ m/^[\+\-]/;
```

?

**Comment by Vogtinator** [comment] 2021-09-21 08:55
I'd try `next unless $line =~ m/^[-+]/;`

**Comment by DimStar77** [comment] 2021-09-21 08:56
> I'd try `next unless $line =~ m/^[-+]/;`

might work - I never know when one needs to escape + and -; the + not being escaped was the original bug, but then it was not inside []

**Comment by coolo** [comment] 2021-09-21 09:02
I don't think we want that either. we want to accept patches *removed* to appear in -, not added patches.

**Comment by DimStar77** [comment] 2021-09-21 09:04
> I don't think we want that either. we want to accept patches _removed_ to appear in -, not added patches.

in case of a revert SR, both might show: added and removed patches

**Comment by coolo** [comment] 2021-09-21 09:07
True. a revert wouldn't add any changes, but could still add or remove patches. I was thinking about the SLE case

**Comment by jreidinger** [comment] 2021-09-21 12:21
OK, I check mentioned pull request and code do what is expected to do. It sees a patch removal, that is not mentioned in changelog. But what it can do is to also see removal of patch addition in diff of old and new changelog. And in such case it should also remove it from list of patches that needs to be mentioned in changelog, right?
@coolo @DimStar77 do I write expected behavior correctly?

**Comment by jreidinger** [comment] 2021-09-21 12:23
When I think about it, one think can be no longer catched and it is if someone just use older version of package, so diff is negative and it won't complain. But I expect it should be catched by different parts as it does not necessary contain Patch.

**Comment by coolo** [comment] 2021-09-21 12:39
Basically: As soon as ^\- appear in the changes, noone expects anything anymore :(

**Comment by jreidinger** [comment] 2021-09-22 21:07
Should be fixed with https://github.com/openSUSE/openSUSE-release-tools/pull/2648

**Comment by jreidinger** [comment] 2021-09-23 12:30
fix merged, so lets close this issue. Feel free to reopen if it does not help and add specific case where it failed so I can enhance test suite to avoid future breakage.

**Closed by jreidinger** 2021-09-23 12:30 UTC
